[tool.pylint.messages_control]
disable=[
        "suppressed-message",
        # therefore we wouldn't have to install full dependency set in order to lint
        "import-error",
        # sometimes we create a dataclass or Pydantic module and just don't need public methods
        "too-few-public-methods",
        # below is handled by pycln
        "unused-import",
        # below is handled by isort
        "wrong-import-order",
        # too restrictive
        "too-many-instance-attributes",
        # not necessary nor useful in our projects
        "missing-module-docstring",
        # we need to import locally to not import optional packages
        "import-outside-toplevel"
        ]

[tool.pylint.format]
max-line-length=120
